name: Android Wear OS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Compile Wear OS module
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v6

      - name: Configurar Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Dar permiso de ejecución a Gradle
        run: chmod +x gradlew

      - name: Compilar proyecto
        run: ./gradlew build --no-daemon

      - name: Generar APK Wear OS
        run: ./gradlew :wearable:assembleDebug --no-daemon

      - name: Guardar APK generado
        uses: actions/upload-artifact@v4
        with:
          name: SafeCare-WearOS-debug-apk
          path: wearable/build/outputs/apk/debug/wearable-debug.apk
          if-no-files-found: error
